- name: install keepalived
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - keepalived

- name: keepalived configuration
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify:
    - restart keepalived

- name: keepalived service
  systemd:
    name: keepalived
    enabled: yes
